// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CargaDeEncuestasInternas.Models.DwhSchema.Entities.StgSchema;


namespace CargaDeEncuestasInternas.Models.DwhSchema.Entities.StgSchema;

public partial class Encuestas
{
    public int idStaging { get; set; }

    public string IdOpinion { get; set; }

    public string IdCliente { get; set; }

    public string IdProducto { get; set; }

    public string Fecha { get; set; }

    public string Comentario { get; set; }

    public string Clasificacion { get; set; }

    public string PuntajeSatisfaccion { get; set; }

    public DateTime FechaExtraccion { get; set; }

    public string FuenteOrigen { get; set; }

    public string EstadoProcesamiento { get; set; }
}