// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CargaDeEncuestasInternas.Models.DwhSchema.Entities.StgSchema;


namespace CargaDeEncuestasInternas.Models.DwhSchema.Entities.StgSchema;

public partial class LogExtraccion
{
    public int idLog { get; set; }

    public DateTime FechaInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public string FuenteOrigen { get; set; }

    public int RegistrosExtraidos { get; set; }

    public int RegistrosConError { get; set; }

    public string Estado { get; set; }

    public string MensajeError { get; set; }
}