// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CargaDeEncuestasInternas.Models.DwhSchema.Entities.StgSchema;


namespace CargaDeEncuestasInternas.Models.DwhSchema.Entities.StgSchema;

public partial class Resenas
{
    public int idStaging { get; set; }

    public int IdOpinionGlobal { get; set; }

    public int IdCliente { get; set; }

    public int IdProducto { get; set; }

    public string Fecha { get; set; }

    public string Comentario { get; set; }

    public byte? Rating { get; set; }

    public DateTime FechaExtraccion { get; set; }

    public string FuenteOrigen { get; set; }

    public string EstadoProcesamiento { get; set; }
}