// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CargaDeEncuestasInternas.Models.dboSchema;


namespace CargaDeEncuestasInternas.Models.dboSchema;

public partial class ComentarioSocial
{
    public int idOpinionGlobal { get; set; }
}