// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CargaDeEncuestasInternas.Models.dboSchema;


namespace CargaDeEncuestasInternas.Models.dboSchema;

public partial class Fuentes
{
    public int idFuente { get; set; }

    public int idCanal { get; set; }

    public DateOnly FechaCarga { get; set; }
}