// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CargaDeEncuestasInternas.Models.dboSchema;


namespace CargaDeEncuestasInternas.Models.dboSchema;

public partial class Opiniones
{
    public int idOpinionGlobal { get; set; }

    public string CodigoOriginal { get; set; }

    public string Comentario { get; set; }

    public DateOnly Fecha { get; set; }

    public int idProducto { get; set; }

    public int idFuente { get; set; }

    public int idCliente { get; set; }
}