// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EncuestasInternas.Entities.Configurations;
using EncuestasInternas.Entities.DimSchema;
using EncuestasInternas.Entities.FactSchema;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace EncuestasInternas.Entities;

public partial class DWHOpinionesClientesContext : DbContext
{
    public DWHOpinionesClientesContext(DbContextOptions<DWHOpinionesClientesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Canal> Canal { get; set; }

    public virtual DbSet<Clasificacion> Clasificacion { get; set; }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<Opiniones> Opiniones { get; set; }

    public virtual DbSet<Producto> Producto { get; set; }

    public virtual DbSet<Tiempo> Tiempo { get; set; }

    public virtual DbSet<TipoOpinion> TipoOpinion { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.CanalConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ClasificacionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ClienteConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.OpinionesConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TiempoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TipoOpinionConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
