// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CargaDeEncuestasInternas.Models.Configurations;
using CargaDeEncuestasInternas.Models.dboSchema;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace CargaDeEncuestasInternas.Models;

public partial class OpinionesClientesContext : DbContext
{
    public OpinionesClientesContext(DbContextOptions<OpinionesClientesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cat_Canal> Cat_Canal { get; set; }

    public virtual DbSet<Cat_TiposCanal> Cat_TiposCanal { get; set; }


    public virtual DbSet<ComentarioSocial> ComentarioSocial { get; set; }


    public virtual DbSet<Fuentes> Fuentes { get; set; }

    public virtual DbSet<Opiniones> Opiniones { get; set; }

    public virtual DbSet<Resena> Resena { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.Cat_CanalConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.Cat_TiposCanalConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ComentarioSocialConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.FuentesConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.OpinionesConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ResenaConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
