// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EncuestasInternas.Entities.DimSchema;
using EncuestasInternas.Entities.FactSchema;


namespace EncuestasInternas.Entities.DimSchema;

public partial class Clasificacion
{
    public int idClasificacion { get; set; }

    public string Etiqueta { get; set; }

    public bool EsPositiva { get; set; }
}