// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EncuestasInternas.Entities.DimSchema;
using EncuestasInternas.Entities.FactSchema;


namespace EncuestasInternas.Entities.DimSchema;

public partial class Cliente
{
    public int idCliente { get; set; }

    public string NombreCliente { get; set; }

    public string Email { get; set; }

    public string Pais { get; set; }

    public string Segmento { get; set; }
}