// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EncuestasInternas.Entities.DimSchema;
using EncuestasInternas.Entities.FactSchema;


namespace EncuestasInternas.Entities.DimSchema;

public partial class Producto
{
    public int idProducto { get; set; }

    public string NombreProducto { get; set; }

    public string Categoria { get; set; }
}