// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EncuestasInternas.Entities.DimSchema;
using EncuestasInternas.Entities.FactSchema;


namespace EncuestasInternas.Entities.DimSchema;

public partial class Tiempo
{
    public int idTiempo { get; set; }

    public DateOnly Fecha { get; set; }

    public short Anio { get; set; }

    public byte Trimestre { get; set; }

    public byte Mes { get; set; }

    public string NombreMes { get; set; }

    public byte Semana { get; set; }

    public byte DiaSemana { get; set; }

    public string NombreDia { get; set; }

    public bool EsFinDeSemana { get; set; }
}