// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EncuestasInternas.Entities.DimSchema;
using EncuestasInternas.Entities.FactSchema;


namespace EncuestasInternas.Entities.DimSchema;

public partial class TipoOpinion
{
    public int idTipoOpinion { get; set; }

    public string Descripcion { get; set; }
}