// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CargaDeEncuestasInternas.Models;
using CargaDeEncuestasInternas.Models.dboSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CargaDeEncuestasInternas.Models.Configurations
{
    public partial class Cat_CanalConfiguration : IEntityTypeConfiguration<Cat_Canal>
    {
        public void Configure(EntityTypeBuilder<Cat_Canal> entity)
        {
            entity.HasKey(e => e.idCanal);

            entity.Property(e => e.idCanal).ValueGeneratedNever();
            entity.Property(e => e.NombreCanal)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Cat_Canal> entity);
    }
}
