// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CargaDeEncuestasInternas.Models;
using CargaDeEncuestasInternas.Models.dboSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CargaDeEncuestasInternas.Models.Configurations
{
    public partial class Cat_TiposCanalConfiguration : IEntityTypeConfiguration<Cat_TiposCanal>
    {
        public void Configure(EntityTypeBuilder<Cat_TiposCanal> entity)
        {
            entity.HasKey(e => e.idTipoCanal);

            entity.Property(e => e.idTipoCanal).ValueGeneratedNever();
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Cat_TiposCanal> entity);
    }
}
