// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CargaDeEncuestasInternas.Models.DwhSchema.Entities.Configurations;
using CargaDeEncuestasInternas.Models.DwhSchema.Entities.StgSchema;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace CargaDeEncuestasInternas.Models.DwhSchema.Entities;

public partial class DWHOpinionesClientesContext : DbContext
{
    public DWHOpinionesClientesContext(DbContextOptions<DWHOpinionesClientesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ComentariosSociales> ComentariosSociales { get; set; }

    public virtual DbSet<Encuestas> Encuestas { get; set; }

    public virtual DbSet<LogExtraccion> LogExtraccion { get; set; }

    public virtual DbSet<Resenas> Resenas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.ComentariosSocialesConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EncuestasConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LogExtraccionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ResenasConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
