// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EncuestasInternas.Entities.DimSchema;
using EncuestasInternas.Entities.FactSchema;


namespace EncuestasInternas.Entities.FactSchema;

public partial class Opiniones
{
    public long idHecho { get; set; }

    public int idTiempo { get; set; }

    public int idCanal { get; set; }

    public int idProducto { get; set; }

    public int idCliente { get; set; }

    public int idClasificacion { get; set; }

    public int idTipoOpinion { get; set; }

    public string CodigoOriginal { get; set; }

    public byte? PuntajeSatisfaccion { get; set; }

    public byte? Rating { get; set; }

    public byte EsPositiva { get; set; }

    public byte EsNegativa { get; set; }

    public byte EsNeutra { get; set; }

    public byte ConteoOpinion { get; set; }
}