// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CargaDeEncuestasInternas.Models.DwhSchema.Entities;
using CargaDeEncuestasInternas.Models.DwhSchema.Entities.StgSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CargaDeEncuestasInternas.Models.DwhSchema.Entities.Configurations
{
    public partial class EncuestasConfiguration : IEntityTypeConfiguration<Encuestas>
    {
        public void Configure(EntityTypeBuilder<Encuestas> entity)
        {
            entity.HasKey(e => e.idStaging).HasName("PK_Stg_Encuestas");

            entity.ToTable("Encuestas", "Stg");

            entity.Property(e => e.Clasificacion).HasMaxLength(50);
            entity.Property(e => e.Comentario).HasMaxLength(500);
            entity.Property(e => e.EstadoProcesamiento)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("PENDIENTE");
            entity.Property(e => e.Fecha)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.FechaExtraccion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FuenteOrigen)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("CSV");
            entity.Property(e => e.IdCliente)
                .IsRequired()
                .HasMaxLength(25);
            entity.Property(e => e.IdOpinion)
                .IsRequired()
                .HasMaxLength(25);
            entity.Property(e => e.IdProducto)
                .IsRequired()
                .HasMaxLength(25);
            entity.Property(e => e.PuntajeSatisfaccion).HasMaxLength(10);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Encuestas> entity);
    }
}
