// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CargaDeEncuestasInternas.Models.DwhSchema.Entities;
using CargaDeEncuestasInternas.Models.DwhSchema.Entities.StgSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CargaDeEncuestasInternas.Models.DwhSchema.Entities.Configurations
{
    public partial class LogExtraccionConfiguration : IEntityTypeConfiguration<LogExtraccion>
    {
        public void Configure(EntityTypeBuilder<LogExtraccion> entity)
        {
            entity.HasKey(e => e.idLog).HasName("PK_Stg_LogExtraccion");

            entity.ToTable("LogExtraccion", "Stg");

            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("EN_PROCESO");
            entity.Property(e => e.FechaFin).HasColumnType("datetime");
            entity.Property(e => e.FechaInicio).HasColumnType("datetime");
            entity.Property(e => e.FuenteOrigen)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.MensajeError).HasMaxLength(1000);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LogExtraccion> entity);
    }
}
