// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CargaDeEncuestasInternas.Models;
using CargaDeEncuestasInternas.Models.dboSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CargaDeEncuestasInternas.Models.Configurations
{
    public partial class ComentarioSocialConfiguration : IEntityTypeConfiguration<ComentarioSocial>
    {
        public void Configure(EntityTypeBuilder<ComentarioSocial> entity)
        {
            entity.HasKey(e => e.idOpinionGlobal);

            entity.Property(e => e.idOpinionGlobal).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ComentarioSocial> entity);
    }
}
