// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CargaDeEncuestasInternas.Models;
using CargaDeEncuestasInternas.Models.dboSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CargaDeEncuestasInternas.Models.Configurations
{
    public partial class FuentesConfiguration : IEntityTypeConfiguration<Fuentes>
    {
        public void Configure(EntityTypeBuilder<Fuentes> entity)
        {
            entity.HasKey(e => e.idFuente);

            entity.Property(e => e.idFuente).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Fuentes> entity);
    }
}
