// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CargaDeEncuestasInternas.Models;
using CargaDeEncuestasInternas.Models.dboSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CargaDeEncuestasInternas.Models.Configurations
{
    public partial class OpinionesConfiguration : IEntityTypeConfiguration<Opiniones>
    {
        public void Configure(EntityTypeBuilder<Opiniones> entity)
        {
            entity.HasKey(e => e.idOpinionGlobal);

            entity.Property(e => e.idOpinionGlobal).ValueGeneratedNever();
            entity.Property(e => e.CodigoOriginal)
                .IsRequired()
                .HasMaxLength(25);
            entity.Property(e => e.Comentario)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Opiniones> entity);
    }
}
