// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EncuestasInternas.Entities;
using EncuestasInternas.Entities.DimSchema;
using EncuestasInternas.Entities.FactSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EncuestasInternas.Entities.Configurations
{
    public partial class CanalConfiguration : IEntityTypeConfiguration<Canal>
    {
        public void Configure(EntityTypeBuilder<Canal> entity)
        {
            entity.HasKey(e => e.idCanal).HasName("PK_Dim_Canal");

            entity.ToTable("Canal", "Dim");

            entity.HasIndex(e => e.TipoCanal, "IX_Dim_Canal_Tipo");

            entity.Property(e => e.NombreCanal)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TipoCanal)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Canal> entity);
    }
}
