// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EncuestasInternas.Entities;
using EncuestasInternas.Entities.DimSchema;
using EncuestasInternas.Entities.FactSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EncuestasInternas.Entities.Configurations
{
    public partial class ClasificacionConfiguration : IEntityTypeConfiguration<Clasificacion>
    {
        public void Configure(EntityTypeBuilder<Clasificacion> entity)
        {
            entity.HasKey(e => e.idClasificacion).HasName("PK_Dim_Clasificacion");

            entity.ToTable("Clasificacion", "Dim");

            entity.Property(e => e.idClasificacion).ValueGeneratedNever();
            entity.Property(e => e.Etiqueta)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Clasificacion> entity);
    }
}
