// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EncuestasInternas.Entities;
using EncuestasInternas.Entities.DimSchema;
using EncuestasInternas.Entities.FactSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EncuestasInternas.Entities.Configurations
{
    public partial class OpinionesConfiguration : IEntityTypeConfiguration<Opiniones>
    {
        public void Configure(EntityTypeBuilder<Opiniones> entity)
        {
            entity.HasKey(e => e.idHecho)
                .HasName("PK_Fact_Opiniones")
                .IsClustered(false);

            entity.ToTable("Opiniones", "Fact");

            entity.Property(e => e.CodigoOriginal)
                .IsRequired()
                .HasMaxLength(25);
            entity.Property(e => e.ConteoOpinion).HasDefaultValue((byte)1);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Opiniones> entity);
    }
}
