// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EncuestasInternas.Entities;
using EncuestasInternas.Entities.DimSchema;
using EncuestasInternas.Entities.FactSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EncuestasInternas.Entities.Configurations
{
    public partial class ProductoConfiguration : IEntityTypeConfiguration<Producto>
    {
        public void Configure(EntityTypeBuilder<Producto> entity)
        {
            entity.HasKey(e => e.idProducto).HasName("PK_Dim_Producto");

            entity.ToTable("Producto", "Dim");

            entity.HasIndex(e => e.Categoria, "IX_Dim_Producto_Categoria");

            entity.Property(e => e.idProducto).ValueGeneratedNever();
            entity.Property(e => e.Categoria)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.NombreProducto)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Producto> entity);
    }
}
