// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EncuestasInternas.Entities;
using EncuestasInternas.Entities.DimSchema;
using EncuestasInternas.Entities.FactSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EncuestasInternas.Entities.Configurations
{
    public partial class TiempoConfiguration : IEntityTypeConfiguration<Tiempo>
    {
        public void Configure(EntityTypeBuilder<Tiempo> entity)
        {
            entity.HasKey(e => e.idTiempo).HasName("PK_Dim_Tiempo");

            entity.ToTable("Tiempo", "Dim");

            entity.HasIndex(e => new { e.Anio, e.Mes }, "IX_Dim_Tiempo_AnioMes");

            entity.Property(e => e.idTiempo).ValueGeneratedNever();
            entity.Property(e => e.NombreDia)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.NombreMes)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Tiempo> entity);
    }
}
