// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EncuestasInternas.Entities;
using EncuestasInternas.Entities.DimSchema;
using EncuestasInternas.Entities.FactSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EncuestasInternas.Entities.Configurations
{
    public partial class TipoOpinionConfiguration : IEntityTypeConfiguration<TipoOpinion>
    {
        public void Configure(EntityTypeBuilder<TipoOpinion> entity)
        {
            entity.HasKey(e => e.idTipoOpinion).HasName("PK_Dim_TipoOpinion");

            entity.ToTable("TipoOpinion", "Dim");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TipoOpinion> entity);
    }
}
